using System.Collections.Generic;

namespace mint.paint.Localization
{
    public static class Strings
    {
        private static Dictionary<string, string> current = Russian;

        public static void SetLanguage(string lang)
        {
            current = lang == "en" ? English : Russian;
        }

        public static string Get(string key) => current.ContainsKey(key) ? current[key] : key;

        private static Dictionary<string, string> Russian = new Dictionary<string, string>
        {
            // Menu headers
            ["File"] = "Файл",
            ["Edit"] = "Правка",
            ["View"] = "Вид",
            ["Color"] = "Цвет",
            ["Layers"] = "Слои",
            ["Brush"] = "Кисть",
            ["Shapes"] = "Фигуры",
            ["Menu_Settings"] = "Настройки",
            
            // File menu
            ["New"] = "Новый",
            ["Open"] = "Открыть...",
            ["Save"] = "Сохранить",
            
            // Edit menu
            ["Undo"] = "Отменить",
            ["Redo"] = "Повторить",
            ["Cut"] = "Вырезать",
            ["Copy"] = "Копировать",
            ["Paste"] = "Вставить",
            ["Delete"] = "Удалить",
            
            // Tools
            ["Tool_Brush"] = "Инструмент: Кисть (B)",
            ["Tool_Eraser"] = "Инструмент: Ластик (E)",
            ["Tool_Fill"] = "Инструмент: Заливка (G)",
            ["Tool_Eyedropper"] = "Инструмент: Пипетка (I)",
            ["Tool_Line"] = "Инструмент: Линия (L)",
            ["Tool_Rectangle"] = "Инструмент: Прямоугольник (R)",
            ["Tool_Circle"] = "Инструмент: Круг (C)",
            ["Tool_Selection"] = "Инструмент: Выделение (S)",
            ["Tool_Text"] = "Инструмент: Текст (T)",
            
            // Common
            ["Size"] = "Размер:",
            ["Hardness"] = "Жесткость:",
            ["Opacity"] = "Непрозрачность:",
            ["OK"] = "OK",
            ["Cancel"] = "Отмена",
            ["Apply"] = "Применить",
            ["Close"] = "Закрыть",
            ["BrushInfo"] = "Кисть: {0}px, {1}% жесткость",
            ["Layer"] = "Слой: {0} ({1}%)",
            ["Grid"] = "Сетка: {0}",
            ["On"] = "вкл",
            ["Off"] = "выкл",
            
            // Menu items
            ["New"] = "Новый",
            ["Open"] = "Открыть...",
            ["Save"] = "Сохранить",
            ["ResizeCanvas"] = "Изменить размер холста...",
            ["Undo"] = "Отменить",
            ["Redo"] = "Повторить",
            ["Cut"] = "Вырезать",
            ["Copy"] = "Копировать",
            ["Paste"] = "Вставить",
            ["Delete"] = "Удалить",
            ["ClearSelection"] = "Снять выделение",
            ["HideTools"] = "Скрыть инструментарий",
            ["ShowRulers"] = "Показать линейки",
            ["Navigator"] = "Навигатор",
            ["ShowGrid"] = "Показать сетку",
            ["SnapToGrid"] = "Привязка к сетке",
            ["ShowLayers"] = "Показать слои",
            ["ColorPalette"] = "Палитра цветов...",
            ["SwapColors"] = "Поменять цвета местами",
            ["NewLayer"] = "Новый слой",
            ["DeleteLayer"] = "Удалить слой",
            ["MergeVisible"] = "Объединить видимые",
            ["ShowLayersPanel"] = "Показать панель слоев",
            ["BrushPresets"] = "Пресеты кистей",
            ["IncreaseBrush"] = "Увеличить кисть",
            ["DecreaseBrush"] = "Уменьшить кисть",
            ["ResetBrush"] = "Сбросить кисть",
            ["Line"] = "Линия",
            ["Rectangle"] = "Прямоугольник",
            ["Circle"] = "Круг",
            ["Gradient"] = "Градиент",
            ["Settings"] = "Настройки...",
            ["About"] = "О программе...",
            
            // Toolbar
            ["ApplySelection"] = "✓ Применить выделение",
            ["Shape"] = "Фигура:",
            ["Style"] = "Стиль:",
            ["Normal"] = "Обычный",
            ["Radial"] = "Круговой",
            ["Reflected"] = "Отраженный",
            ["AddStops"] = "Добавить ограничители",
            ["Font"] = "Шрифт:",
            ["Alignment"] = "Выравнивание:",
            ["Left"] = "Влево",
            ["Center"] = "Центр",
            ["Right"] = "Вправо",
            ["DropSize"] = "Размер капель:",
            ["Count"] = "Количество:",
            ["UndoButton"] = "Отменить",
            ["RedoButton"] = "Повторить",
            ["CutButton"] = "Вырезать",
            ["CopyButton"] = "Копировать",
            ["PasteButton"] = "Вставить",
            
            // Status bar
            ["Coordinates"] = "X: {0}, Y: {1}",
            
            // Settings window
            ["SettingsTitle"] = "Настройки",
            ["AppSettings"] = "Настройки приложения",
            ["Palette"] = "Палитра",
            ["Special"] = "Особое",
            ["CustomPalettes"] = "Пользовательские палитры:",
            ["Add"] = "Добавить",
            ["Remove"] = "Удалить",
            ["Language"] = "Язык:",
            ["UndoSteps"] = "Шагов отмены:",
            ["AutoUpdate"] = "Включить автообновления",
            
            // Layers window
            ["LayersTitle"] = "Слои",
            ["AddLayer"] = "Добавить слой",
            ["RemoveLayer"] = "Удалить слой",
            ["MergeLayers"] = "Объединить видимые",
            ["Options"] = "Параметры",
            ["ShowInactiveLayers"] = "Показывать невидимые слои на холсте",
            ["InactiveOpacity"] = "Прозрачность невидимых слоев",
            ["AutoLayerText"] = "Добавлять новый слой при добавлении текста",
            ["MergeSameColors"] = "Объединить слои с одинаковыми цветами...",
            ["MoveUp"] = "↑ Вверх",
            ["MoveDown"] = "↓ Вниз",
            ["LayerEffects"] = "⚡ Эффекты слоя",
            
            // Navigator window
            ["NavigatorTitle"] = "Навигатор",
            
            // Resize Canvas window
            ["ResizeCanvasTitle"] = "Изменить размер холста",
            ["Width"] = "Ширина:",
            ["Height"] = "Высота:",
            
            // Presets window
            ["PresetsTitle"] = "Пресеты кистей и шрифтов",
            ["Brushes"] = "Кисти",
            ["Fonts"] = "Шрифты",
            ["BrushPresets"] = "Пресеты кистей",
            ["CustomBrushes"] = "Пользовательские кисти",
            ["CreatePreset"] = "➕ Создать пресет",
            ["TextSettings"] = "Настройки текста",
            ["FontFamily"] = "Шрифт",
            ["LoadFont"] = "Загрузить шрифт...",
            ["Bold"] = "Жирный",
            ["Italic"] = "Курсив",
            ["TextSize"] = "Размер текста",
            ["AlignLeft"] = "По левому краю",
            ["AlignCenter"] = "По центру",
            ["AlignRight"] = "По правому краю",
            ["TextPreview"] = "Пример текста",
            ["Watercolor"] = "💧 Акварель",
            ["Normal"] = "🖌 Обычная",
            ["Pencil"] = "✏️ Карандаш",
            ["Pixel"] = "⬛ Пиксели",
            ["Drops"] = "💦 Капли",
            ["SoftRound"] = "Мягкая круглая",
            ["HardRound"] = "Жесткая круглая",
            ["Oil"] = "Масло",
            
            // Layer Effects window
            ["LayerEffectsTitle"] = "Эффекты слоя",
            ["Shadow"] = "Тень",
            ["Enable"] = "Включить",
            ["Color"] = "Цвет:",
            ["OffsetX"] = "Смещение X:",
            ["OffsetY"] = "Смещение Y:",
            ["Blur"] = "Размытие:",
            ["OuterGlow"] = "Внешнее свечение",
            ["Bevel3D"] = "3D эффект",
            ["Type"] = "Тип:",
            ["Emboss"] = "Выпуклость",
            ["Engrave"] = "Углубление",
            ["Depth"] = "Глубина:",
            
            // Palette Editor window
            ["PaletteEditorTitle"] = "Редактор палитры",
            ["PaletteName"] = "Название палитры:",
            ["MyPalette"] = "Моя палитра",
            ["AddColor"] = "Добавить цвет",
            ["Save"] = "Сохранить",
            
            // Color Picker window
            ["ColorPickerTitle"] = "Палитра цветов",
            ["MoreSettings"] = "▼ Больше настроек",
            ["LessSettings"] = "▲ Меньше настроек",
            ["HSLSettings"] = "HSL настройки",
            ["RGBSettings"] = "RGB настройки",
            ["Hue"] = "Оттенок (Hue):",
            ["Saturation"] = "Насыщенность (Saturation):",
            ["Lightness"] = "Яркость (Lightness):",
            ["Red"] = "Красный (R):",
            ["Green"] = "Зеленый (G):",
            ["Blue"] = "Синий (B):",
            ["ColorApplied"] = "Цвет применяется автоматически",
            
            // Gradient Stops Editor
            ["StopsEditor"] = "Редактор ограничителей",
            ["SelectColor"] = "Выбрать цвет...",
            ["Position"] = "Положение",
            ["Load"] = "Загрузить",
            ["LoadGradient"] = "Загрузить градиент",
            ["SaveGradient"] = "Сохранить градиент",
            ["Gradients"] = "Градиенты (*.grd)|*.grd",
            ["LoadError"] = "Ошибка загрузки градиента",
            ["SaveError"] = "Ошибка сохранения градиента",
            ["Error"] = "Ошибка",
            ["Success"] = "Успех",
            ["Info"] = "Информация",
            ["Done"] = "Готово",
            ["Restart"] = "Перезапуск",
            ["Confirmation"] = "Подтверждение",
            ["Warning"] = "Предупреждение",
            ["MergedLayers"] = "Объединено слоев: {0}",
            ["NoSameColors"] = "Не найдено слоев с одинаковыми цветами",
            ["OpenFileError"] = "Ошибка открытия файла: {0}",
            ["SaveFileError"] = "Ошибка сохранения: {0}",
            ["SaveChanges"] = "Сохранить изменения?",
            ["UnsavedChanges"] = "Несохраненные изменения",
            ["EnterPaletteName"] = "Введите название палитры!",
            ["AddOneColor"] = "Добавьте хотя бы один цвет!",
            ["FontLoaded"] = "Шрифт '{0}' загружен",
            ["FontLoadError"] = "Ошибка загрузки шрифта: {0}",
            ["EnterValidSize"] = "Введите корректные размеры",
            ["LanguageChanged"] = "Язык изменен. Перезапустите приложение.",
            ["SettingsApplied"] = "Настройки применены!",
            ["ClearCanvas"] = "Очистить весь холст?",
            ["CreateBrushPreset"] = "Создать пресет кисти",
            ["Name"] = "Название:",
            ["NewBrush"] = "Новая кисть",
            ["Create"] = "Создать",
            ["RenameLayer"] = "Переименовать слой",
            ["NewName"] = "Новое название:",
            
            // About window
            ["About_Title"] = "О программе",
            ["About_Version"] = "Версия 1.0.0",
            ["About_Description"] = "Графический редактор для рисования и редактирования изображений",
            ["About_Copyright"] = "© misdon технологии 2025",
            ["CheckUpdates"] = "Проверить обновления",
            ["CheckingUpdates"] = "Проверка обновлений...",
        };

        private static Dictionary<string, string> English = new Dictionary<string, string>
        {
            // Menu headers
            ["File"] = "File",
            ["Edit"] = "Edit",
            ["View"] = "View",
            ["Color"] = "Color",
            ["Layers"] = "Layers",
            ["Brush"] = "Brush",
            ["Shapes"] = "Shapes",
            ["Menu_Settings"] = "Settings",
            
            // File menu
            ["New"] = "New",
            ["Open"] = "Open...",
            ["Save"] = "Save",
            
            // Edit menu
            ["Undo"] = "Undo",
            ["Redo"] = "Redo",
            ["Cut"] = "Cut",
            ["Copy"] = "Copy",
            ["Paste"] = "Paste",
            ["Delete"] = "Delete",
            
            // Tools
            ["Tool_Brush"] = "Tool: Brush (B)",
            ["Tool_Eraser"] = "Tool: Eraser (E)",
            ["Tool_Fill"] = "Tool: Fill (G)",
            ["Tool_Eyedropper"] = "Tool: Eyedropper (I)",
            ["Tool_Line"] = "Tool: Line (L)",
            ["Tool_Rectangle"] = "Tool: Rectangle (R)",
            ["Tool_Circle"] = "Tool: Circle (C)",
            ["Tool_Selection"] = "Tool: Selection (S)",
            ["Tool_Text"] = "Tool: Text (T)",
            
            // Common
            ["Size"] = "Size:",
            ["Hardness"] = "Hardness:",
            ["Opacity"] = "Opacity:",
            ["OK"] = "OK",
            ["Cancel"] = "Cancel",
            ["Apply"] = "Apply",
            ["Close"] = "Close",
            ["BrushInfo"] = "Brush: {0}px, {1}% hardness",
            ["Layer"] = "Layer: {0} ({1}%)",
            ["Grid"] = "Grid: {0}",
            ["On"] = "on",
            ["Off"] = "off",
            
            // Menu items
            ["New"] = "New",
            ["Open"] = "Open...",
            ["Save"] = "Save",
            ["ResizeCanvas"] = "Resize Canvas...",
            ["Undo"] = "Undo",
            ["Redo"] = "Redo",
            ["Cut"] = "Cut",
            ["Copy"] = "Copy",
            ["Paste"] = "Paste",
            ["Delete"] = "Delete",
            ["ClearSelection"] = "Clear Selection",
            ["HideTools"] = "Hide Tools",
            ["ShowRulers"] = "Show Rulers",
            ["Navigator"] = "Navigator",
            ["ShowGrid"] = "Show Grid",
            ["SnapToGrid"] = "Snap to Grid",
            ["ShowLayers"] = "Show Layers",
            ["ColorPalette"] = "Color Palette...",
            ["SwapColors"] = "Swap Colors",
            ["NewLayer"] = "New Layer",
            ["DeleteLayer"] = "Delete Layer",
            ["MergeVisible"] = "Merge Visible",
            ["ShowLayersPanel"] = "Show Layers Panel",
            ["BrushPresets"] = "Brush Presets",
            ["IncreaseBrush"] = "Increase Brush",
            ["DecreaseBrush"] = "Decrease Brush",
            ["ResetBrush"] = "Reset Brush",
            ["Line"] = "Line",
            ["Rectangle"] = "Rectangle",
            ["Circle"] = "Circle",
            ["Gradient"] = "Gradient",
            ["Settings"] = "Settings...",
            ["About"] = "About...",
            
            // Toolbar
            ["ApplySelection"] = "✓ Apply Selection",
            ["Shape"] = "Shape:",
            ["Style"] = "Style:",
            ["Normal"] = "Normal",
            ["Radial"] = "Radial",
            ["Reflected"] = "Reflected",
            ["AddStops"] = "Add Stops",
            ["Font"] = "Font:",
            ["Alignment"] = "Alignment:",
            ["Left"] = "Left",
            ["Center"] = "Center",
            ["Right"] = "Right",
            ["DropSize"] = "Drop Size:",
            ["Count"] = "Count:",
            ["UndoButton"] = "Undo",
            ["RedoButton"] = "Redo",
            ["CutButton"] = "Cut",
            ["CopyButton"] = "Copy",
            ["PasteButton"] = "Paste",
            
            // Status bar
            ["Coordinates"] = "X: {0}, Y: {1}",
            
            // Settings window
            ["SettingsTitle"] = "Settings",
            ["AppSettings"] = "Application Settings",
            ["Palette"] = "Palette",
            ["Special"] = "Special",
            ["CustomPalettes"] = "Custom Palettes:",
            ["Add"] = "Add",
            ["Remove"] = "Remove",
            ["Language"] = "Language:",
            ["UndoSteps"] = "Undo Steps:",
            ["AutoUpdate"] = "Enable Auto-Updates",
            
            // Layers window
            ["LayersTitle"] = "Layers",
            ["AddLayer"] = "Add Layer",
            ["RemoveLayer"] = "Remove Layer",
            ["MergeLayers"] = "Merge Visible",
            ["Options"] = "Options",
            ["ShowInactiveLayers"] = "Show Inactive Layers on Canvas",
            ["InactiveOpacity"] = "Inactive Layers Opacity",
            ["AutoLayerText"] = "Add New Layer When Adding Text",
            ["MergeSameColors"] = "Merge Layers with Same Colors...",
            ["MoveUp"] = "↑ Move Up",
            ["MoveDown"] = "↓ Move Down",
            ["LayerEffects"] = "⚡ Layer Effects",
            
            // Navigator window
            ["NavigatorTitle"] = "Navigator",
            
            // Resize Canvas window
            ["ResizeCanvasTitle"] = "Resize Canvas",
            ["Width"] = "Width:",
            ["Height"] = "Height:",
            
            // Presets window
            ["PresetsTitle"] = "Brush and Font Presets",
            ["Brushes"] = "Brushes",
            ["Fonts"] = "Fonts",
            ["BrushPresets"] = "Brush Presets",
            ["CustomBrushes"] = "Custom Brushes",
            ["CreatePreset"] = "➕ Create Preset",
            ["TextSettings"] = "Text Settings",
            ["FontFamily"] = "Font",
            ["LoadFont"] = "Load Font...",
            ["Bold"] = "Bold",
            ["Italic"] = "Italic",
            ["TextSize"] = "Text Size",
            ["AlignLeft"] = "Align Left",
            ["AlignCenter"] = "Align Center",
            ["AlignRight"] = "Align Right",
            ["TextPreview"] = "Sample Text",
            ["Watercolor"] = "💧 Watercolor",
            ["Normal"] = "🖌 Normal",
            ["Pencil"] = "✏️ Pencil",
            ["Pixel"] = "⬛ Pixel",
            ["Drops"] = "💦 Drops",
            ["SoftRound"] = "Soft Round",
            ["HardRound"] = "Hard Round",
            ["Oil"] = "Oil",
            
            // Layer Effects window
            ["LayerEffectsTitle"] = "Layer Effects",
            ["Shadow"] = "Shadow",
            ["Enable"] = "Enable",
            ["Color"] = "Color:",
            ["OffsetX"] = "Offset X:",
            ["OffsetY"] = "Offset Y:",
            ["Blur"] = "Blur:",
            ["OuterGlow"] = "Outer Glow",
            ["Bevel3D"] = "3D Effect",
            ["Type"] = "Type:",
            ["Emboss"] = "Emboss",
            ["Engrave"] = "Engrave",
            ["Depth"] = "Depth:",
            
            // Palette Editor window
            ["PaletteEditorTitle"] = "Palette Editor",
            ["PaletteName"] = "Palette Name:",
            ["MyPalette"] = "My Palette",
            ["AddColor"] = "Add Color",
            ["Save"] = "Save",
            
            // Color Picker window
            ["ColorPickerTitle"] = "Color Palette",
            ["MoreSettings"] = "▼ More Settings",
            ["LessSettings"] = "▲ Less Settings",
            ["HSLSettings"] = "HSL Settings",
            ["RGBSettings"] = "RGB Settings",
            ["Hue"] = "Hue:",
            ["Saturation"] = "Saturation:",
            ["Lightness"] = "Lightness:",
            ["Red"] = "Red (R):",
            ["Green"] = "Green (G):",
            ["Blue"] = "Blue (B):",
            ["ColorApplied"] = "Color applied automatically",
            
            // Gradient Stops Editor
            ["StopsEditor"] = "Stops Editor",
            ["SelectColor"] = "Select Color...",
            ["Position"] = "Position",
            ["Load"] = "Load",
            ["LoadGradient"] = "Load Gradient",
            ["SaveGradient"] = "Save Gradient",
            ["Gradients"] = "Gradients (*.grd)|*.grd",
            ["LoadError"] = "Gradient Load Error",
            ["SaveError"] = "Gradient Save Error",
            ["Error"] = "Error",
            ["Success"] = "Success",
            ["Info"] = "Information",
            ["Done"] = "Done",
            ["Restart"] = "Restart",
            ["Confirmation"] = "Confirmation",
            ["Warning"] = "Warning",
            ["MergedLayers"] = "Merged layers: {0}",
            ["NoSameColors"] = "No layers with same colors found",
            ["OpenFileError"] = "File open error: {0}",
            ["SaveFileError"] = "Save error: {0}",
            ["SaveChanges"] = "Save changes?",
            ["UnsavedChanges"] = "Unsaved Changes",
            ["EnterPaletteName"] = "Enter palette name!",
            ["AddOneColor"] = "Add at least one color!",
            ["FontLoaded"] = "Font '{0}' loaded",
            ["FontLoadError"] = "Font load error: {0}",
            ["EnterValidSize"] = "Enter valid dimensions",
            ["LanguageChanged"] = "Language changed. Restart the application.",
            ["SettingsApplied"] = "Settings applied!",
            ["ClearCanvas"] = "Clear entire canvas?",
            ["CreateBrushPreset"] = "Create Brush Preset",
            ["Name"] = "Name:",
            ["NewBrush"] = "New Brush",
            ["Create"] = "Create",
            ["RenameLayer"] = "Rename Layer",
            ["NewName"] = "New Name:",
            
            // About window
            ["About_Title"] = "About",
            ["About_Version"] = "Version 1.0.0",
            ["About_Description"] = "Graphics editor for drawing and image editing",
            ["About_Copyright"] = "© misdon технологии 2025",
            ["CheckUpdates"] = "Check for Updates",
            ["CheckingUpdates"] = "Checking for updates...",
        };
    }
}
